[package]
name = "caseless"
version = "0.2.1"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
description = "Unicode caseless matching"
repository = "https://github.com/unicode-rs/rust-caseless"
license = "MIT"

build = "src/build.rs"

[dependencies]
unicode-normalization = "0.1"
