[package]

name = "caseless"
version = "0.1.3"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
description = "Unicode caseless matching"
repository = "https://github.com/SimonSapin/rust-caseless"
license = "MIT"

build = "src/build.rs"

[build-dependencies]
regex = "0.2"

[dependencies]
unicode-normalization = "0.1"
